### ISSUE TITLE
Bad Syntax in kitana.py?

### ISSUE THREAD

**Issue by tzw9373** [pannal/Kitana#7] opened 2019-05-19 04:10 UTC
I wrote a simple batch file to run my katana instance at startup and noticed recently it wasn't running. When manually running from cmd I see the following info. This is the kitana.py file that comes right from the zip here on Github

"C:\kitana>python kitana.py
  File "kitana.py", line 422
    return template.render(plex_headers_json=json.dumps(self.plex_headers), **self.default_context, servers=servers)
                                                                                                  ^
SyntaxError: invalid syntax"

This is the first I'm seeing this, any thoughts?

**Comment by pannal** [comment] 2019-05-25 23:54
Yep that seems like a bug.

**Comment by pannal** [comment] 2019-05-25 23:56
Does that work now?

**Comment by tzw9373** [comment] 2019-05-27 21:36
Now I'm getting the following when using the updated kitana.py:
C:\kitana>python kitana.py
  File "kitana.py", line 678
    versioned_asset.replace("/", os.sep))}, )
                                          ^
SyntaxError: invalid syntax

**Comment by pannal** [comment] 2019-05-28 11:46
I can't reproduce that locally, it runs fine:
```
D:\data\___small\kitana\venv\Scripts\python.exe D:/data/___small/kitana/kitana.py
[28/May/2019:13:45:18] ENGINE Bus STARTING
[28/May/2019:13:45:18] ENGINE Starting SassCompilerPlugin
[28/May/2019:13:45:18] ENGINE Set handler for console events.
[28/May/2019:13:45:19] ENGINE Serving on http://0.0.0.0:31337
[28/May/2019:13:45:19] ENGINE Bus STARTED
[28/May/2019:13:45:19]  Starting Sass Compile
[28/May/2019:13:45:19]  SassCompilerPlugin: Compiling D:\data\___small\kitana\static\sass to D:\data\___small\kitana\static\css
[28/May/2019:13:45:21] ENGINE Listening for SIGTERM.
No token, redirecting
[28/May/2019:13:45:43] ENGINE Started monitor thread 'Session cleanup'.
```

**Comment by pannal** [comment] 2019-05-28 11:46
How did you check the project out?

**Comment by tzw9373** [comment] 2019-06-17 21:40
How do you mean? I'm still seeing this error, could it possibly be related to the version of Python I'm using? Currently running Anaconda.

**Comment by tzw9373** [comment] 2019-06-20 23:43
I was able to correct the issues I had above but now I'm seeing the following:

C:\kitana>python3.5 kitana.py
Traceback (most recent call last):
  File "kitana.py", line 24, in <module>
    from plugins.SassCompilerPlugin import SassCompilerPlugin
  File "C:\kitana\plugins\SassCompilerPlugin.py", line 47
    cherrypy.log(f'{self.__class__.__name__}: Compiling {dirpath} to {str(css_directory)}')
                                                                                         ^
SyntaxError: invalid syntax

Any thoughts?

**Comment by pannal** [comment] 2019-06-20 23:49
The f' syntax is only supported by Python 3.6. You're on 3.5 :)

**Comment by pannal** [comment] 2019-06-20 23:51
The f' syntax is only supported by Python 3.6. My README is wrong, sorry.

**Comment by pannal** [comment] 2019-06-20 23:53
Wait, no, you forgot to install requirements.txt, didn't you? I've got a drop in feature replacement for that exact issue.

**Comment by tzw9373** [comment] 2019-06-20 23:58
I've installed both requirements files and everything comes back as already satisfied, I'm assuming since I installed previously.

**Comment by pannal** [comment] 2019-06-21 00:23
How did you install them? Are they installed in the correct python installation?

The Docker version of Kitana also uses Python 3.5 successfully, so there's really no issue there.

**Comment by tzw9373** [comment] 2019-06-21 00:31
I ran pip3.5 install -r requirements_win32.txt and confirmed it installed all the modules successfully. They're also installed in Python 2.7 but every command I'm giving it is pointing to 3.5.

**Comment by pannal** [comment] 2019-06-21 01:02
```python3.5 kitana.py
[21/Jun/2019:03:02:03] ENGINE Bus STARTING
[21/Jun/2019:03:02:03] ENGINE Set handler for console events.
[21/Jun/2019:03:02:03] ENGINE Starting SassCompilerPlugin
[21/Jun/2019:03:02:04] ENGINE Serving on http://0.0.0.0:31337
[21/Jun/2019:03:02:04] ENGINE Bus STARTED
[21/Jun/2019:03:02:04]  Starting Sass Compile
[21/Jun/2019:03:02:04]  SassCompilerPlugin: Compiling D:\data\___small\kitana\static\sass to D:\data\___small\kitana\static\css
[21/Jun/2019:03:02:06] ENGINE Listening for SIGTERM.```

**Comment by pannal** [comment] 2019-06-21 01:05
Something's wrong with your setup. How did you "receive" Kitana? Git for windows? Zip download?

**Comment by tzw9373** [comment] 2019-06-21 01:14
I just downloaded a fresh copy of the zip today and re-installed the requirements today.

**Comment by tzw9373** [comment] 2019-06-22 15:06
I installed and ran the program successfully from another computer I have. This one runs Lubuntu, but the Windows one just really doesn't like that syntax in the Sass Plugin.

**Comment by tzw9373** [comment] 2019-06-23 16:38
I tried installing on a second Windows device and it gives me the same invalid syntax error. So it appears to be a Windows only issue, I installed ActivePython as advised and all the requirements were installed correctly.

**Comment by tzw9373** [comment] 2019-07-18 22:51
Any updates on this at all? Here's a screen shot of the separate instance I'm running on a Linux computer.
![snip](https://user-images.githubusercontent.com/50788362/61497301-a75a4900-a984-11e9-8e98-ff3053910820.PNG)
 It's working fine but it's not externally accessible via my Nginx reverse proxy so it's not terribly useful currently.

**Comment by pannal** [comment] 2019-07-19 07:52
Can you try a git checkout instead of downloading the zip? I'm pretty stumped, it works on my Windows installations.

**Comment by tzw9373** [comment] 2019-07-19 10:37
To your Nginx question, I didn't know you could to that. Would you point it to that computer's internal static IP instead of 127.0.0.1 in the conf?

**Comment by pannal** [comment] 2019-07-19 11:33
Exactly.

**Comment by tzw9373** [comment] 2019-07-19 11:45
Well what do you know. Thanks for the tip, I'll give that a shot until I have a chance to look at the git checkout.

**Comment by lukjod** [comment] 2019-08-22 11:35
I have the same after install on qnap aarch64 device

File "kitana.py", line 678
versioned_asset.replace("/", os.sep))}, )
^
SyntaxError: invalid syntax

any help? what logs needed to debug?

**Comment by azza10** [comment] 2019-09-07 12:09
Did you end up figuring this issue out tzw? 
I'm experiencing the exact same syntax error.

Using ActivePython 3.5.4.3504-win64-x64-404899
Clean download and install of requirements using "pip3.5 install -I --no-cache-dir -r requirements_win32.txt"
python3.5 kitana.py

output:
C:\Kitana>python3.5 kitana.py
Traceback (most recent call last):
  File "kitana.py", line 24, in <module>
    from plugins.SassCompilerPlugin import SassCompilerPlugin
  File "C:\Kitana\plugins\SassCompilerPlugin.py", line 47
    cherrypy.log(f'{self.__class__.__name__}: Compiling {dirpath} to {str(css_directory)}')
                                                                                         ^
SyntaxError: invalid syntax

CMD run as administrator.
Win10 pro

**Comment by tzw9373** [comment] 2019-09-07 12:15
I haven't fixed the issue, no. I've been running it on my secondary box, but I have a theory. I think that the command is somehow still running with the Python 2.7 for me, because I got the same error when running "python kitana.py". I checked my path environment and everything appears to be correct there, so I've kinda given up. Sub-Zero is really the only plugin I still use and it doesn't need a lot of babysitting. I've also set up Bazarr to pull subs with Radarr/Sonarr.

**Comment by pannal** [comment] 2019-09-07 19:50
Hmm, can you try the latest master? I've ditched the stringformatf dependency.

I was able to reproduce this on Windows btw:
```
python2.7 kitana.py
  File "kitana.py", line 685
    versioned_asset.replace("/", os.sep))}, )
                                          ^
SyntaxError: invalid syntax
``` 
vs. 
```
python3 kitana.py
[07/Sep/2019:21:47:25] ENGINE Bus STARTING
[07/Sep/2019:21:47:25] ENGINE Set handler for console events.
[07/Sep/2019:21:47:25] ENGINE Starting SassCompilerPlugin
[07/Sep/2019:21:47:25] ENGINE Serving on http://0.0.0.0:31337
[07/Sep/2019:21:47:25] ENGINE Bus STARTED
```

**Comment by tzw9373** [comment] 2019-09-07 21:08
I'm still seeing the same issue as azza10.

**Comment by pannal** [comment] 2019-09-16 19:12
@tzw9373 have you tried explicitly using python3 or python3.5 as the executable?

**Comment by tzw9373** [comment] 2019-09-16 19:27
I've tried python3, python3.5 and python35. All unsuccessfully.

**Comment by pannal** [comment] 2019-09-16 19:28
With the same error and the newest master?

**Comment by tzw9373** [comment] 2019-09-16 20:11
Yep. https://ibb.co/tH07vNs

**Comment by pannal** [comment] 2019-09-17 03:52
You aren't using the latest master: https://github.com/pannal/Kitana/blob/master/plugins/SassCompilerPlugin.py

The future fstrings dependency has been removed for quite a while now.

**Comment by azza10** [comment] 2019-09-17 04:34
Can you explain how to obtain the latest master? I have been doing:
Go to releases
Under assets, download kitana.zip.
Latest version is 0.1.7 for me.

https://photos.app.goo.gl/7uppXzfqmbVLKBB76

**Comment by pannal** [comment] 2019-09-17 06:00
0.1.7 is latest master. Did you remove the old folder or at least deleted the .pyc files?

**Comment by tzw9373** [comment] 2019-09-17 21:10
Guess you're right, it works once I re-downloaded. The updates you made must have been after the one I pulled like 10 days ago.

**Comment by tzw9373** [comment] 2019-09-17 22:27
Somewhat of a separate bug: I have my Kitana instance reverse proxied behind NGINX, but I get the following error when accessing my instance: Mixed Content: https://kitana.xxx.info/token was loaded over HTTPS, but requested an insecure stylesheet 'http://kitana.xxx.info/static/css/main.279e6ad.css'. It also has the same for /static/js/auth.279e6ad.js. My googling suggests I just need those URLs to show as https://kitana.xxx.info/...., but how is that done? I can't find token anywhere in my filesystem.

**Comment by pannal** [comment] 2019-09-18 05:31
Can you post your nginx Config?

**Comment by tzw9373** [comment] 2019-09-18 21:37
Here are the sections inside http { } that pertain:

#load balancer - round robin to Windows 10 server and Ubuntu 18.04 VM
upstream kitana {
	server 127.0.0.1:31337;
	server 192.168.0.191:31337;
	}
#kitana
	server {
    listen 80;
    listen [::]:80;
    server_name kitana.xxx.info;

    return 301 https://$host$request_uri;
}
#HTTPS kitana
    server {
        listen       443 ssl;
        listen       [::]:443 ssl;
        server_name  kitana.xxx.info;
 
        ssl_certificate      C:/LetsEncrypt/ssl/kitana/kitana.xxx.info-chain.pem;
        ssl_certificate_key  C:/LetsEncrypt/ssl/kitana/kitana.xxx.info-key.pem;
 
        ssl_session_cache    shared:SSL:10m;
        ssl_session_timeout  10m;
 
        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;
		
        location / {
		
		    limit_req zone=mylimit burst=20;

            proxy_pass http://kitana;
            
			proxy_set_header    Host                $host;

			proxy_set_header    X-Real-IP           $remote_addr;

			proxy_set_header    X-Forwarded-Host    $server_name;

			proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;

			proxy_set_header    X-Forwarded-Proto   $scheme;

			proxy_set_header    X-Forwarded-Ssl     on;
        }
    }

**Comment by pannal** [comment] 2019-09-19 09:35
Try putting the proxy header directives before the proxy pass.

**Comment by tzw9373** [comment] 2019-09-19 11:14
No dice on that either. From my internet research I get the impression it might be something that's generated by kitana.py or something else that points to http (instead of https) when it builds the page.

**Comment by pannal** [comment] 2019-09-19 15:21
It shouldn't. I'm using kitana myself with both the docker and the standalone version, behind HTTPS, without issues.

I simply can't look for my config right now as I'm on holiday :)

**Comment by pannal** [comment] 2019-09-20 17:46
Wait, how do you spawn kitana @tzw9373?

Have a look at the README, it needs a couple of settings to run behind a reverse proxy: https://github.com/pannal/Kitana#usage

You most likely want `-P -PB https://kitana.xxx.info`

**Comment by tzw9373** [comment] 2019-09-20 17:53
That's docker, right? All my installs are standalone.

**Comment by pannal** [comment] 2019-09-20 18:19
You're still serving Kitana behind a reverse proxy and it needs to know about that.

**Comment by tzw9373** [comment] 2019-09-20 18:20
So those commands are run after python35 kitana.py?

**Comment by pannal** [comment] 2019-09-20 18:24
Yes. As you're running on Windows, this might be advised: `python35 kitana.py -P --shadow-assets=False`

**Comment by tzw9373** [comment] 2019-09-20 21:25
Gotcha. That sorted me out!

**Comment by pannal** [comment] 2019-09-21 03:53
Great! Closing for now.

**Closed** 2019-09-21 03:53 UTC
