### ISSUE TITLE
New SSL conn error cascade on server select - same issue as #33, #34, #35

### ISSUE THREAD

**Issue by RiggiG** [pannal/Kitana#37] opened 2020-04-12 17:29 UTC
issue links for ease #33, #34, #35

Tried with version 0.3.1-3 & 0.3.2 via Docker and standalone (and clone of master standalone) - persists across each. All various connection attempts fail (including relay after re-enabling) fail. 

**Workaround**: explicitly disabling secure connections in the Plex server's Settings->Network (previously set to `Preferred` for me) allows a successful connection. 

[Log from 0.3.2 docker ](https://pastebin.com/k3Y4ykZG)

**Comment by pannal** [comment] 2020-04-13 00:27
Your issue seems different. The machine running Kitana doesn't seem to be able to resolve your plex.direct hostnames (`[Errno -5] No address associated with hostname`).

The other tickets you've linked are related to the SSL protocols/handling themselves, which has been fixed recently.

**Comment by pannal** [comment] 2021-01-23 03:54
Closing for now. Please reopen if still an issue.

**Comment by bitIO** [comment] 2021-01-31 14:52
I've something similar.

`requests.exceptions.SSLError: HTTPSConnectionPool(host='192-168-1-47.76dadadd0ef2466dbf8e5f8ad15f3299.plex.direct', port=32400): Max retries exceeded with url: /video/trakt (Caused by SSLError(SSLCertVerificationError("hostname '192-168-1-47.76dadadd0ef2466dbf8e5f8ad15f3299.plex.direct' doesn't match '*.a5672a53aac94125a3f279ecd0330c5e.plex.direct'")))`

I've tried downgrading, but still go the same error. Workaround by @RiggiG didn't work either

**Comment by pannal** [comment] 2021-02-07 18:06
Can you try 0.4.0-2?

**Comment by yeahpmmx** [comment] 2021-02-09 23:11
Hi there, I think it is related...

Successfully connected to PlexServer 
Timeout on PlexServer 
Error on PlexServer (see log): HTTPConnectionPool(host='xxx.xxx.xxx.xxx', port=32400): Read timed out. (read timeout=15) 

Thanks

**Comment by pannal** [comment] 2021-02-11 15:36
That doesn't look like it's related, but more likely a network issue. Which kind of connection did you ask Kitana to use?

**Comment by yeahpmmx** [comment] 2021-02-11 16:40
ok ok, tried with bot that appear there...

![image](https://user-images.githubusercontent.com/78828472/107667687-73750180-6c55-11eb-81b2-53f35f973ed9.png)

Someone mentioned something a bout the preferred secure network connection, tried to change that as well but no luck.

Thanks again :)

**Comment by pannal** [comment] 2021-02-11 16:50
Hmm. So the PMS isn't inside your network, is it? At least it doesn't advertise as such.

**Comment by yeahpmmx** [comment] 2021-02-11 16:53
Sorry. I forgot to mention that. Nop its not. It's with a provider. Upload speeds around here are kinda trashy so couldn't access it outside my network.

**Comment by pannal** [comment] 2021-02-11 16:58
Hmm OK. Not sure, is the container Kitana's running as able to connect to the outside world? You might want to open a separate issue for this, as this is unrelated (no certificate issue, but routing)

**Comment by Wolf666** [comment] 2021-02-26 10:41
Running kitana 4.0,2 on docker still having this message: 

> requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://192-168-1-100.725690953ec14972b12e2efbf3cd7004.plex.direct:32400/video/trakt

**Comment by pannal** [comment] 2021-02-26 11:43
@Wolf666 different issue, please open a new one with logs.

**Closed** 2021-03-14 02:14 UTC
